### ISSUE TITLE
constant redefinition warnings

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaPlots/PlotlyJS.jl#318]
on julia 1.4 I get the following warnings

```julia
julia> using PlotlyJS

WARNING: redefining constant singleton_instance
WARNING: redefining constant routing_callback
WARNING: redefining constant webio_server_config
```
Don't know if the same happens on previous julia versions

**Comment by sglyon** [comment]
hmm those functions aren't defined (or redefined) in this package. Perhaps someone from the webio world would have a better idea?

cc @travigd @shashi

**Comment by travigd** [comment]
@SimonDanisch I think this is the generic HTTP provider, yeah?

**Comment by SimonDanisch** [comment]
Yeah, sounds like it!

**Comment by shashi** [comment]
I think some of those need to be in __init__ too...

**Comment by sglyon** [comment]
I think this has been resolved, so I will close now. 

If it is still a problem feel free to comment and I can re-open
