### ISSUE TITLE
Move to JuliaPlots

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPlots/PlotlyJS.jl#335]
Hi @sglyon, I wonder if we should move this package over to JuliaPlots so that more folks can help keep it going.

**Comment by sglyon** [comment]
Hey @ViralBShah that'd be ok with me, assuming we think a move of org would help get people involved.

Perhaps we could ping people from JuliaPlots here to see if they'd be willing to help out post move?

**Comment by ViralBShah** [comment]
Yeah, it is hard to predict if it will actually help get people involved, but I am hoping it will. At least for the simple tasks to start with. 

@chrisrackauckas Who all should we ping here?

**Comment by ChrisRackauckas** [comment]
@daschw @BeastyBlacksmith

**Comment by daschw** [comment]
Sure, we can move PlotlyJS over to JuliaPlots. I doubt that I will find much time to contribute and I think the situation is similar for other Plots or Makie developers, but if you think this can attract new contributors I'm certainly fine with that.

**Comment by BeastyBlacksmith** [comment]
If nothing else, at least it makes it easier to keep track of changes of each other.

**Comment by ViralBShah** [comment]
In general, I find that having widely used packages in orgs does attract contributors to fix small bugs, help with maintenance work, and generally give more visibility. Eventually out of this seed, larger contributions build up.

**Comment by sglyon** [comment]
Ok let's do it!

I'd ask that I can retain admin privileges over it, but am happy to have more people involved!

**Comment by ViralBShah** [comment]
Of course, I would suggest, if the JuliaPlots current owners are ok, to also make @sglyon owner of the JuliaPlots org. That's generally how I've done things in other orgs.

**Comment by daschw** [comment]
Done and welcome to JuliaPlots @sglyon!

**Comment by sglyon** [comment]
Thanks -- it's on its way!

**Comment by sglyon** [comment]
I've labeled about 10 issues with "Help wanted". While I'd love help on any issues, I think these ones should be doable by someone with a working knowledge of modern julia and packaging, but without necessarily having a deep knowledge of the PlotlyJS.jl code.

That'd be a great place to start getting some help. If anyone wants to pitch in I'd love that! If you need some help as you get started don't hesitate to reach otu
