### ISSUE TITLE
Link to documentations leads to 404

### ISSUE THREAD

**Issue by Rudi79** [JuliaPlots/PlotlyJS.jl#336]
Hi, it seems that the link to the documentation is broken.

http://spencerlyon.com/PlotlyJS.jl/

just reports a 404

**Comment by sglyon** [comment]
Oh no!

We’ll get this fixed ASAP. Thank you for making us aware

**Comment by Rudi79** [comment]
Any news on this? Can I be of any help with the issue?

**Comment by sglyon** [comment]
Fixed! thanks for the ping

**Comment by sglyon** [comment]
Note that the link is now http://juliaplots.github.io/PlotlyJS.jl
