### ISSUE TITLE
Axis labels don't work with 3D plots

### ISSUE THREAD

**Issue by travelingspaceman** [JuliaPlots/PlotlyJS.jl#347]
The `*axis_title` properties do not work on 3D plots. As a simple example:
```
using PlotlyJS
plot(scatter3d(x=rand(10), y=rand(10), z=rand(10), mode="markers"),
     Layout(xaxis_title="X axis",
            yaxis_title="Y axis",
            zaxis_title="Z axis",
            title="Title"))
```
Produces the following figure (notice the axis labels are still the default): 
![image](https://user-images.githubusercontent.com/25992581/91208858-177ae880-e6c8-11ea-9743-01a67d27412c.png)

**Comment by sglyon** [comment]
I believe for some reason you need to add these properties to the Layout.scene property

Something like this should work:


```
using PlotlyJS
plot(scatter3d(x=rand(10), y=rand(10), z=rand(10), mode="markers"),
     Layout(scene=attr(xaxis_title="X axis",
            yaxis_title="Y axis",
            zaxis_title="Z axis",
            title="Title")))
```

**Comment by travelingspaceman** [comment]
That works, thanks!
