### ISSUE TITLE
plotlyjs() gives an error without ORCA

### ISSUE THREAD

**Issue by Ossifragus** [JuliaPlots/PlotlyJS.jl#349]
**Describe the bug**
When I use `plotlyjs()` to switch the backend, I got the following error

ERROR: ArgumentError: Package ORCA not found in current path:
-Run `import Pkg; Pkg.add("ORCA")` to install the ORCA package.

However, ORCA.jl is deprecated (https://github.com/sglyon/ORCA.jl), and if I add it, I have the following warning.

┌ Warning: ORCA.jl has been deprecated and all savefig functionality
│ has been implemented directly in PlotlyBase itself.
│ 
│ By implementing in PlotlyBase.jl, the savefig routines are automatically
│ available to PlotlyJS.jl also.
└ @ ORCA ~/.julia/packages/ORCA/U5XaN/src/ORCA.jl:8

Should I keep ORCA for now?

**Version info**

Please provide the following:

1. output of julia command `versioninfo()`

Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = 4

2. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.status()`)

  [ad839575] Blink v0.12.3
  [336ed68f] CSV v0.7.7
  [a93c6f00] DataFrames v0.21.7
  [31c24e10] Distributions v0.23.11
  [becb17da] Feather v0.5.6
  [09f84164] HypothesisTests v0.10.0
  [b964fa9f] LaTeXStrings v1.1.0
  [ff71e718] MixedModels v2.3.1
  [47be7bcc] ORCA v0.5.0
  [a03496cd] PlotlyBase v0.4.1
  [f0f68f2c] PlotlyJS v0.14.0
  [91a5bcdd] Plots v1.6.2
  [c3e4b0f8] Pluto v0.11.11
  [6f49c342] RCall v0.13.7
  [79098fc4] Rmath v0.6.1
  [2913bbd2] StatsBase v0.33.1
  [f3b207a7] StatsPlots v0.14.11
  [44d3d7a6] Weave v0.10.3

**Comment by sglyon** [comment]
@Ossifragus you can keep ORCA for now

All ORCA does is import PlotlyBase.savefig, re-export it, and then issue this warning . The whole package is in this file: https://github.com/sglyon/ORCA.jl/blob/5410f8d14c271d63366bfa8514e7807ca6a25334/src/ORCA.jl

Hopefully we can get this sorted out soon and the warning will go away!

**Comment by Ossifragus** [comment]
@sglyon Got it. Thank you very much for the quick response and detailed information!
