### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghuba** [JuliaPlots/PlotlyJS.jl#353]
I noticed a few things in the doc:

http://juliaplots.org/PlotlyJS.jl/stable/

`exporting figures`
has the wrong link:
http://juliaplots.org/PlotlyJS.jl/manipulating_plots/#saving-figures
It should be:
http://juliaplots.org/PlotlyJS.jl/stable/manipulating_plots/#Saving-figures

Also there are a coupe of weird things on the main page:

http://juliaplots.org/PlotlyJS.jl/stable/

![image](https://user-images.githubusercontent.com/4511360/93406348-4b1edd80-f844-11ea-8a33-28c6c31b17eb.png)

`[plotly.js][_plotlyjs]`

`[plotlyjs]: https://plot.ly/javascript [plotlyref]: https://plotly.com/javascriptreference`

`plotly graphics to files`

**Comment by BeastyBlacksmith** [comment]
fixed in db72a942deea1ba0c21f3d8679ff9da6f38a5fe2
