### ISSUE TITLE
All plots output blank Atom window while the saved .html figures are normal.

### ISSUE THREAD

**Issue by deltaeecs** [JuliaPlots/PlotlyJS.jl#370]
All figures showing on Atom went blank after update PlotlyJS from v0.14.0 to v0.14.1. 
I checked the saved ".html" figures with browser and they are all well.

Output:
![image](https://user-images.githubusercontent.com/48714525/111575756-0b808080-87ea-11eb-94d9-1d2e741a4f3a.png)
Saved figure:
![image](https://user-images.githubusercontent.com/48714525/111575897-5601fd00-87ea-11eb-93e8-8a2a92214676.png)

Julia Version 1.6.0-rc2
Commit 4b6b9fe4d7 (2021-03-11 07:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia

      Status `C:\Users\delta\.julia\environments\v1.6\Project.toml`
  [6e4b80f9] BenchmarkTools v0.6.0
  [ad839575] Blink v0.12.4
  [28b8d3ca] GR v0.55.0
  [42fd0dbc] IterativeSolvers v0.9.0
  [652e05fd] JuliaZH v1.5.4
  [f0f68f2c] PlotlyJS v0.14.1
  [91a5bcdd] Plots v1.10.6
  [92933f4c] ProgressMeter v1.5.0
  [90137ffa] StaticArrays v1.0.1
  [b189fb0b] ThreadPools v1.2.1
  [37e2e46d] LinearAlgebra
  [10745b16] Statistics

**Comment by jonas-kr** [comment]
Please feel free to try whether
```
]add https://github.com/jonas-kr/PlotlyJS.jl
```
resolves your issue. See also #372 .

**Comment by claytonpbarrows** [comment]
I can confirm that I had this issue and that your branch solves it.

**Comment by deltaeecs** [comment]
> Please feel free to try whether
> 
> ```
> ]add https://github.com/jonas-kr/PlotlyJS.jl
> ```
> 
> resolves your issue. See also #372 .

Thx, I just test your solution it worked!
