### ISSUE TITLE
I got nothing: no plot

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaPlots/PlotlyJS.jl#383]
**Describe the bug**
From the documentation
```
using PlotlyJS
function area1()
    trace1 = scatter(;x=1:4, y=[0, 2, 3, 5], fill="tozeroy")
    trace2 = scatter(;x=1:4, y=[3, 5, 1, 7], fill="tonexty")
    plot([trace1, trace2])
end
area1()
```
I got a blank window, no warning, no error.

**Version info**

Please provide the following:

julia> versioninfo()                                                           
Julia Version 1.6.1                                                            
Commit 6aaedecc44 (2021-04-23 05:59 UTC)                                       
Platform Info:                                                                 
  OS: Windows (x86_64-w64-mingw32)                                             
  CPU: Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz                                
  WORD_SIZE: 64                                                                
  LIBM: libopenlibm                                                            
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)                                       
Environment:                                                                   
  JULIA_SSL_CA_ROOTS_PATH =                                                    
                                                                               
julia> using Pkg; Pkg.status();                                                
      Status `C:\Users\PetrKrysl\.julia\environments\v1.6\Project.toml`        
  [f0f68f2c] PlotlyJS v0.14.1                                                  
  [295af30f] Revise v3.1.16                                                    
                                                                               
julia> 
1. output of julia command `versioninfo()`
2. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.status()`)

**Comment by PetrKryslUCSD** [comment]
Appears to have been solved by https://github.com/JuliaPlots/PlotlyJS.jl/issues/377#issuecomment-861797863

**Comment by sglyon** [comment]
Thank you for letting me know. I'm working right now on revamping (simplyfing) the display system

In short, I'll be removing many of the interactive features and suggesting that users go to Dash.jl for that functionality

**Comment by PetrKryslUCSD** [comment]
I hope that doesn't include zoom, panning, and rotation? I really rely on all the tools in the tool bar:
![image](https://user-images.githubusercontent.com/9855832/122582443-07dcdf80-d00d-11eb-900f-54d0a40a9869.png)

**Comment by sglyon** [comment]
Nope those will stay!
