### ISSUE TITLE
Hover functionality in histograms

### ISSUE THREAD

**Issue by PatMcFarlane** [JuliaPlots/PlotlyJS.jl#388]
I'm using plots.jl with the PlotlyJS backend and the hover functionality doesn't seem to work when plotting histograms.

I'm doing all my plotting in VSCode so plots render in the VSCode plot window.   But even if I use the popdisplay() command so that they render in a browser, the problem still persists.

The examples on the plotlyjs website have the hover feature working just fine though:

[https://plotly.com/javascript/histograms/](url)

**Comment by sglyon** [comment]
I'm sorry, this might be an issue with Plots.jl -- could you reopen there?
