### ISSUE TITLE
What happened to the options in 0.16?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaPlots/PlotlyJS.jl#390]
I used to produce plots as:
```
pl = plot(plots, layout; options=Dict(:plotlyServerURL=>"https://chart-studio.plotly.com", :showSendToCloud=>true, :showLink => true))
```
Version 0.16 does not accept options any more. How do I supply these selections?

**Comment by PetrKryslUCSD** [comment]
Treatment of options: this example from the docs does not work:
```
plot(rand(10, 4), options=Dict(:staticPlot => true))
```

**Comment by PetrKryslUCSD** [comment]
This looks like a solution: https://discourse.julialang.org/t/can-one-set-configuration-options-using-plotlyjs-jl/40357/4

**Comment by PetrKryslUCSD** [comment]
The documentation (syncplot.md) needs to be updated to reflect this change of API.

**Comment by sglyon** [comment]
Thank you for catching this!

**Comment by sglyon** [comment]
http://juliaplots.org/PlotlyJS.jl/dev/syncplots/#Display-configuration done!
