### ISSUE TITLE
No plot is displayed with version 0.16.4

### ISSUE THREAD

**Issue by empet** [JuliaPlots/PlotlyJS.jl#392]
I installed PlotlyJS.jl v 0.16.4, but no plot is displayed. The plot is saved as png or html file, though. So I'll switch back to @jonas-kr's  version. Does anyone else have this issue?

**Comment by jonas-kr** [comment]
I have been running the newest release successfully and cannot reproduce this behavior. Have you already tried to removing and reinstalling PlotlyJS? Maybe there is something off regarding the dependencies.

**Comment by sglyon** [comment]
Can you provide a little more detail? What frontend are you using? Terminal/Jupyter/VS Code /etc.?

**Comment by empet** [comment]
I have Julia 1.6.1 and code running in  Jupyter Notebook. I removed the package PlotlyJS, as @jonas-kr advised, and reinstalled it, but the plots are not displayed.

```
julia> versioninfo
versioninfo (generic function with 2 methods)

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA = C:\Users\empet\....\Julia-1.6.1\bin
```

**Comment by empet** [comment]
I installed the last version and the issue persists. Could someone point out how it can be fixed, by your experience with the same behaviour manifested before, for version 0.15?

**Comment by mzaffalon** [comment]
If you update to the latest version v0.18 the problem appears to be solved.

**Comment by empet** [comment]
@mzaffalon In the last post I omitted to point out that  the last version is  0.18.0. It did not fix the issue :(

**Comment by jonas-kr** [comment]
@empet Unfortunately, I cannot reproduce your issue in JupyterLab. I am using PlotlyJS 0.18 together with IJulia 1.23.2. Have you tried setting up your julia environment from scratch?

**Comment by mzaffalon** [comment]
@empet : what [was](https://discourse.julialang.org/t/not-a-question-but-a-3d-plotlyjs-gallery/65063) the problem?

**Comment by empet** [comment]
> @empet Unfortunately, I cannot reproduce your issue in JupyterLab. I am using PlotlyJS 0.18 together with IJulia 1.23.2. Have you tried setting up your julia environment from scratch?

Thank you for suggestion! I'll do it.

**Comment by sglyon** [comment]
I think I'm going to close here, but please reopen and/or comment if this is still a problem.

Thanks!
