### ISSUE TITLE
Too many entries in  subplots legends

### ISSUE THREAD

**Issue by empet** [JuliaPlots/PlotlyJS.jl#407]
I experimented `make_subplots()`, and I noticed that for two subplots with a trace each one I get a legend with 4 traces:
```
using PlotlyJS
include("plotlyju.jl")
pl = make_subplots(rows=1, cols=2, horizontal_spacing=0.04, 
                   subplot_titles=permutedims(["Title 1", "Title 2"]))
pl.plot.style=plotlyju
add_trace!(pl, scatter(x=1:5, y=rand(2:7, 5)), row=1, col=1)
add_trace!(pl, scatter(x=-2:3, y=rand(1:9, 6)), row=1, col=2)
    
relayout!(pl, title_text="Subplots", width=600, height=300)
```
![Subplots-with-titles](https://user-images.githubusercontent.com/3627253/128318001-924a2ec4-13fe-40dd-92b4-b5fecd05b6b3.png)
If I remove plotlyju style, the legend is also displaying four traces, but with  distinct colors:
![Subplots-no-style](https://user-images.githubusercontent.com/3627253/128319587-d75f5a3e-a596-4095-8bce-9181e9311751.png)

**Comment by sglyon** [comment]
whoa this is definitely not supposed to happen. I'll take a look!

**Comment by sglyon** [comment]
fixed !
