### ISSUE TITLE
Problems with lens and yflip

### ISSUE THREAD

**Issue by RibeiroAndre** [JuliaPlots/PlotlyJS.jl#417]
**Describe the bug**
Trying to use lens with yflip is giving me strange results. In one case, the grey line connecting the lens to its box is in the wrong place. In another case, the original plot gets unflipped.
```
using Plots
plotlyjs()
plot(rand(100),rand(100),yflip=true)
lens!([0,.2], [0,.2], inset = (1, bbox(0.35, 0.0, 0.4, 0.4)), yflip=true)
```
**Version info**
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

[f0f68f2c] PlotlyJS v0.18.7
[91a5bcdd] Plots v1.21.3

**Comment by sglyon** [comment]
Hmm -- seems like a Plots.jl issue. I suggest checking with them!
