### ISSUE TITLE
style

### ISSUE THREAD

**Issue by IgorDouven** [JuliaPlots/PlotlyJS.jl#418]
I hadn't used the package for a while, then went back to old code which does use it, but now I'm finding that the default style is (I'd say) the default style from R's `ggplot` package (grayish background, title no longer centered, etc.). Is there a way to switch back to the old style? The documentation says there are in-built styles, but I can't find them, neither in the documentation nor in the source code.

**Comment by empet** [comment]
@IgorDouven 
I addressed the same question some time ago and @sglyon  suggested [here, in a closed issue](https://github.com/JuliaPlots/PlotlyJS.jl/issues/408),  how to define my own template.
- To center the plot title, define `layout=Layout(title_text="Your title", title_x=0.5)`. 
- For any  data attribute or layout see: [https://plotly.com/julia/reference/](https://plotly.com/julia/reference/),
- Tutorials for almost each trace type are available here [https://plotly.com/julia/](https://plotly.com/julia/).

**Comment by IgorDouven** [comment]
Thanks, that's very helpful (though I'm sorry to hear these changes were
made).

Op zo 3 okt. 2021 om 19:54 schreef Math-Python & Julia <
***@***.***>:

**Comment by IgorDouven** [comment]
That's very useful, thank you!

Op ma 4 okt. 2021 om 17:04 schreef Spencer Lyon ***@***.***>:
