### ISSUE TITLE
Style and documentation

### ISSUE THREAD

**Issue by ghuba** [JuliaPlots/PlotlyJS.jl#419]
**Describe the bug**

The `Style` function is no longer supported.

I also noticed a recent commit:

https://github.com/JuliaPlots/PlotlyJS.jl/commit/f837a34350e3253e690afe515457c52553fdf8c1

"remove styles from docs as they are not supported anymore"

But for some reason `Style` still appears in the documentation:

http://juliaplots.org/PlotlyJS.jl/stable/styles/

Unless somehow this is an outdated documentation page?

Anyways I wanted to confirm that `Style` is gone, and in that case point out that the documentation was not updated correctly following this commit. I am not sure what is going on exactly though. Confusing...

Thanks!

**Comment by sglyon** [comment]
Definitely confusing! 

Perhaps the docs failed to deploy??

Style is indeed gone and has been replaced by the officially supported `layout.template` functionality.

**Comment by ghuba** [comment]
OK. Thanks!  🙂
