### ISSUE TITLE
kaleido/savefig for any objects outside PlotlyJS.jl

### ISSUE THREAD

**Issue by joshday** [JuliaPlots/PlotlyJS.jl#435]
It appears (https://github.com/JuliaComputing/PlotlyLight.jl/issues/8) that `PlotlyJS.savefig` works out of the box for `PlotlyLight.Plot`s if you simply remove the type annotations in the `savefig` code.

How would ya'll feel about one of these options?

1. Put the `savefig` code in its own package.  Then PlotlyJS wouldn't need to depend on Kaliedo_jll.
2. Remove the type annotations in the `savefig` code, so other Plotly packages could take advantage of it.

**Comment by sglyon** [comment]
I’d be happy to get this working. Perhaps it belongs in Kaliedo package?

can you elaborate more on what you were thinking with (1)

**Comment by disberd** [comment]
Somehow related to https://github.com/JuliaPlots/PlotlyJS.jl/issues/428

**Comment by BeastyBlacksmith** [comment]
I'm much in favor of having a seperate package for saving plotly plots to different output formats.
Soft-pinning PlotlyBase to 0.7 in Plots is beginning to hurt and I'd rather avoid having `Kaleido_jll` as a direct dependency.

**Comment by sglyon** [comment]
@BeastyBlacksmith happy to consider something here. What would you propose?

**Comment by BeastyBlacksmith** [comment]
I'm with @joshday here to create a Kaleido.jl package that takes a json-string and the desired output format and a target path and then creates a file.

**Comment by joshday** [comment]
Any volunteers to create it?  I'll get to it next week (probably) if there are no takers.

**Comment by sglyon** [comment]
Yeah I think all the code is out there. Copy/paste to move it to a separate package should be the way forward.

The only potential issue is deciding how dependencies flow. Will PlotlyJS.jl depend on Kaleido.jl? If so, what types will  be used for the `savefig` methods in the Kaleido.jl source (if you look at `src/kaledio.jl` you see we are using types from both PlotlyJS.jl and PlotlyBase.jl)

**Comment by BeastyBlacksmith** [comment]
> Will PlotlyJS.jl depend on Kaleido.jl? If so, what types will be used for the `savefig` methods in the Kaleido.jl source (if you look at `src/kaledio.jl` you see we are using types from both PlotlyJS.jl and PlotlyBase.jl)

I'd say Kaleido.jl should be agnostic to any types and just work on the string representation of the plot. So I'd change that and then PlotlyJS.jl would convert its Plot objects to string before passing it to Kaleido.jl.

**Comment by BeastyBlacksmith** [comment]
I made a first version here: https://github.com/JuliaPlots/Kaleido.jl
