### ISSUE TITLE
UndefVarError: setexcludinghandlers! not defined

### ISSUE THREAD

**Issue by ryofurue** [JuliaPlots/PlotlyJS.jl#440]
The following code 
````
using Plots
plotlyjs() # without this line, this code generates a static graph.
plot(0:10, sin.((0:10)/3))
````
keeps emitting
````
UndefVarError: setexcludinghandlers! not defined
Stacktrace:
  [1] set_nosync(ob::Observables.Observable{Dict{Any, Any}}, val::Dict{String, Any})
. . . .
````
when run as `include("try.jnl")` from the julia REPL.

Julia 1.7.3 (2022-05-06)
macOS 12.5

(up to date with juliaup).

**Edit:**  Having kept searching the Net after my initial post, I finally found this discussion:

https://bytemeta.vip/repo/JuliaGizmos/WebIO.jl/issues/493

where a temporary workaround is shown:   pin the package `WebIO` to  version 0.8.17 .  That has worked for me.

**Comment by mzaffalon** [comment]
More specifically here: https://github.com/JuliaGizmos/WebIO.jl/issues/493#issuecomment-1175841764.

**Comment by ryofurue** [comment]
@mzaffalon 

> More specifically here: https://github.com/JuliaGizmos/WebIO.jl/issues/493#issuecomment-1175841764.

Thank you for that. (By the way, your post made me sure that there must be a functionality to get a link to each individual comment in a thread and I was able to find the function.)

**Comment by mzaffalon** [comment]
Yes, under the three dots on the top right side of the post you want to link there is a copy link entry in the menu.

**Comment by deltaeecs** [comment]
Still the same problem on my windows 10, 11 and ubuntu 2004.

**Comment by BeastyBlacksmith** [comment]
I can't replicate that with PlolyJS v0.18.8 and WebIO v0.8.18
```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, rocketlake)
  Threads: 1 on 16 virtual cores
```

**Comment by mzaffalon** [comment]
@BeastyBlacksmith did you hover with the cursor over the graph line? I still see the error message with Julia 1.8,1.

**Comment by empet** [comment]
@BeastyBlacksmith,
With a simple  scatter plot, it works, but if the Plot involves many traces based on a large data set, then after displaying the plot, it is also displayed this error. Julia 1 7.3, PlotlyJS 0.18.8, and WebIO, 0.18.8.
