### ISSUE TITLE
Config is ignored

### ISSUE THREAD

**Issue by StepanSushko** [JuliaPlots/PlotlyJS.jl#444]
**Describe the bug**
When I try to prevent modeBar to appear or be static, it is still visible! Also modeBarButtonsToRemove is ignored, I tried examples from here https://plotly.com/julia/configuration-options/

**Version info**

Please provide the following:

1. output of julia command `versioninfo()`:
        Julia Version 1.7.2
        Commit bf53498635 (2022-02-06 15:21 UTC)
        Platform Info:
          OS: Windows (x86_64-w64-mingw32)
          CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
          WORD_SIZE: 64
          LIBM: libopenlibm
          LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
        Environment:
          JULIA_NUM_THREADS = 11 ./julia
          JULIA_EDITOR = code
3. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.status()`)
        [336ed68f] CSV v0.10.4
        [1b08a953] Dash v1.1.2
        [1b08a953] DashBootstrapComponents v1.2.1
        [a93c6f00] DataFrames v1.3.5
        [31c24e10] Distributions v0.25.70
        [5789e2e9] FileIO v1.15.0
        [bb4c363b] GridInterpolations v1.1.2
        [033835bb] JLD2 v0.4.23
        [a40420fb] LocalApproximationValueIteration v0.4.3
        [db97f5ab] LocalFunctionApproximation v1.1.0
        [08074719] POMDPModelTools v0.3.13
        [355abbd5] POMDPModels v0.4.16
        [182e52fb] POMDPPolicies v0.4.3
        [e0d0a172] POMDPSimulators v0.3.14
        [a93abf59] POMDPs v0.9.5
        [d96e819e] Parameters v0.12.3
        [f0f68f2c] PlotlyJS v0.18.8
        [3aa3ecc9] QMDP v0.1.6
        [8af83fb2] QuickPOMDPs v0.2.13
        [295af30f] Revise v3.4.0
        [fdbf4ff8] XLSX v0.8.4
        [ade2ca70] Dates
        [10745b16] Statistics

**Comment by StepanSushko** [comment]
I've managed to work only the following code:
` plot(   scatter(
                    mode="markers",
                    x=[1, 2, 3],
                    y=[1, 3, 1]
                ),
                Layout(
                    modebar_remove=["pan", "zoom", "zoomin", "zoomout", "autoscale", "resetScale", "select", "lasso", "logomark"])
            )`

**Comment by StepanSushko** [comment]
If someone is interested in the case of Dash config works:
`dcc_graph(id = "figure1", figure = figures1, config=Dict( "displayModeBar" => false))`

**Comment by empet** [comment]
With Julia 1.7.3, PlotlyJS 0.18.8 it works:
```
using PlotlyJS
fig= Plot(scatter(x=-1 .+2*rand(10), 
                  y=3*rand(10), mode="markers"), 
          Layout(width=450, height=300);
          config=PlotConfig(displayModeBar=true, 
                            linkText="https://plotly.com/julia/reference",
                            showLink=true))
```
![PlotConfig](https://user-images.githubusercontent.com/3627253/192852249-8fd1fd57-bbc1-4fd2-b041-f5794ced593f.jpg)

**Comment by chrisnekarda** [comment]
This has regressed as of PlotlyJS v0.18.15 with Julia 1.11.1. The `config` options are ignored.

```
using PlotlyJS
fig = Plot(scatter(x=-1 .+ 2 * rand(10),
        y=3 * rand(10), mode="markers"),
    Layout(width=450, height=300);
    config=PlotConfig(displayModeBar=false,
        linkText="https://plotly.com/julia/reference",
        showLink=true))
```

yields

![Screenshot 2024-11-07 at 09 15 04](https://github.com/user-attachments/assets/1a0aa53b-440d-408e-8d69-248a0a6e78cc)

where I've moused over the image to expose the mode bar.

```
julia> versioninfo()
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m3)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_EDITOR = code

pkg> st
Status `/private/var/folders/rt/mtl5z3l567q60njy54s_g3780000gn/T/jl_GhLEvC/Project.toml`
  [f0f68f2c] PlotlyJS v0.18.15
```

**Comment by jd-foster** [comment]
@chrisnekarda Is this plot done inside VS Code? If so, can you try doing it directly from a terminal + Julia REPL?
This difference is that opening in the HTML plot in the browser appears to have the link, while VS Code does not - I wonder if you can also see this?

**Comment by chrisnekarda** [comment]
> @chrisnekarda Is this plot done inside VS Code? If so, can you try doing it directly from a terminal + Julia REPL? This difference is that opening in the HTML plot in the browser appears to have the link, while VS Code does not - I wonder if you can also see this?

Worked as expected at the terminal/Safari, just not in VSC. So it's a bug somewhere in the VS Code plots browser. I'll open an issue there. Thanks and sorry to misattribute.

**Comment by jd-foster** [comment]
It's not completely misattributed since it's up to PlotlyJS to extend the right method/MIME type here - I'll look into what we can do on this side.

**Comment by jd-foster** [comment]
Ok, this should be fixed in the next VSCode Julia extension release.
