### ISSUE TITLE
No figures produced by plot commands in code, except the final one

### ISSUE THREAD

**Issue by oscarvdvelde** [JuliaPlots/PlotlyJS.jl#457]
**Describe the bug**

When executing this from a code window in VS Code:

using PlotlyJS
p = plot(rand(10, 4))
q = plot(rand(10, 4))
r = plot(rand(10, 4))

--> only the last one is actually creating a figure. 
When running the code in the REPL it creates three figures. Typing p or q in the REPL will create the figures.
I have seen more substantial plot commands take time to process between println output, but fail to display any figure while the execution moves on.

**Version info**

Julia Version 1.8.3
Commit 0434deb161 (2022-11-14 20:14 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

Status `C:\Users\oscar\.julia\environments\v1.8\Project.toml`
  [336ed68f] CSV v0.10.8
  [e9467ef8] GLMakie v0.8.0
  [85f8d34a] NCDatasets v0.12.11
  [30363a11] NetCDF v0.11.7
  [f0f68f2c] PlotlyJS v0.18.10
  [91a5bcdd] Plots v1.38.0
  [2913bbd2] StatsBase v0.33.21
  [10745b16] Statistics

**Comment by oscarvdvelde** [comment]
I can now get it to show by adding display(p) etc. after each plot statement. 

Sorry in case this is not a bug, I am new to Julia. 
Oscar

**Comment by mzaffalon** [comment]
@oscarvdvelde if all is OK, can you please close this issue?
