### ISSUE TITLE
[Question] Plotting points over box plot in PlotlyJS Julia

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaPlots/PlotlyJS.jl#458]
This is a [cross-post](https://stackoverflow.com/questions/74968571/plotting-points-over-box-plot-in-plotlyjs-julia).  
I would like to plot data points over a box plot in PlotlyJS in Julia. Here is some reproducible code to create a box plot with data points side by side:
```julia
using PlotlyJS, CSV, DataFrames
df = dataset(DataFrame, "tips")
PlotlyJS.plot(df, x=:time, y=:total_bill, boxpoints="all", kind="box")
```
Output:

[![enter image description here][1]][1]

As you can see it nicely plots the data points and box plot side by side, but I would like to add the point on top of the box plot. In plotly python we may use `stripmode = "overlay"`, but this doesn't work for PlotlyJS. So I was wondering if anyone knows how to add the points on top of the box plot?

  [1]: https://i.stack.imgur.com/b9u8C.png

**Comment by empet** [comment]
Just insert `pointpos=0` in the last line:
```
PlotlyJS.plot(df, x=:time, y=:total_bill, boxpoints="all", kind="box")
```
and the points are plotted over boxes.
There is no `stripmode` attribute for `Plotly.JS.box` or the python version `go.Box`. Perhaps you saw somewhere a figure defined by the Plotly Express function `px.strip`, which can be called with stripmode="overlay" or `stripmode="group"`.

**Comment by shayandavoodii** [comment]
Thank you so much. I got it!
